spring.application.name=orderService
server.port=7072

# Datasource config (example, update per your DB)
spring.datasource.url=jdbc:postgresql://localhost:5432/orderappdb
spring.datasource.username=postgres
spring.datasource.password=1103
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true


# Kafka bootstrap servers
spring.kafka.bootstrap-servers=localhost:9092

# Consumer group id - unique for order service
spring.kafka.consumer.group-id=order-service-group

# Key deserializer (assuming keys are strings)
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Value deserializer (JsonDeserializer to convert JSON back to DTO)
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Tell Kafka what class to deserialize the value into
spring.kafka.consumer.properties.spring.json.value.default.type=orderService.orderService.dto.OrderKafkaDto
spring.kafka.consumer.properties.spring.json.type.mapping=order:orderService.orderService.dto.OrderKafkaDto

# Trust packages for JsonDeserializer (your DTO packages or '*' for all)
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# Disable auto commit for manual control (recommended in transactional flows)
spring.kafka.consumer.enable-auto-commit=false

# Offset reset policy: where to start if no offset found (earliest to get all data)
spring.kafka.consumer.auto-offset-reset=earliest

# Kafka listener concurrency (number of threads consuming in parallel)
spring.kafka.listener.concurrency=1

# Topic name used in your listener
kafka.topic.customer-placed-order=customer-placed-order-topic